name: Build
on:
  push:
jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        mode: [ Debug, ReleaseSafe, ReleaseFast ]
        target: [ native, x86_64-linux-gnu, x86_64-windows-gnu, aarch64-windows-gnu, x86_64-macos, aarch64-macos ]
    name: ${{ matrix.os }}, ${{ matrix.target }}-${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        if:  matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update 
          sudo apt-get install -y xorg-dev build-essential libudev-dev libasound2 libasound2-dev libpipewire-0.3-0 libpipewire-0.3-dev libjack-jackd2-0 libjack-jackd2-dev libpulse-dev libpulse0

      - uses: actions/checkout@v3
      - name: Checkout submodules, configure git
        run: |
          git submodule update --init --recursive --depth 0 
          
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.2063+804cee3b9
          
      - name: Build 
        if: matrix.os == 'windows-latest'
        run: zig build -Doptimize=${{ matrix.mode }} -Dtarget=${{ matrix.target }} -j1
          
      - name: Build 
        if: matrix.os != 'windows-latest'
        run: zig build -Doptimize=${{ matrix.mode }} -Dtarget=${{ matrix.target }}

      - name: Upload
        if: matrix.os == 'ubuntu-latest' && matrix.target != 'native'
        uses: actions/upload-artifact@v3
        with:
          path: zig-out/bin
          name: ${{ matrix.target }} - ${{ matrix.mode }}